<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { WrightstoneMemoryDisable, WrightstoneMemoryEnable, WrightstoneMemoryGetOptions, WrightstoneMemoryGetStatus, WrightstoneMemoryUpdate } from '../../wailsjs/go/main/App'
import { translate as t } from '../i18n'
import SigilMemoryPicker from './SigilMemoryPicker.vue'
const emit = defineEmits(['status'])
const status = reactive({ found:false, hooked:false, selectedAddr:0, firstHash:0, firstName:'', firstLevel:0, secondHash:0, secondName:'', secondLevel:0, thirdHash:0, thirdName:'', thirdLevel:0 })
const form = reactive({ firstHash:0, firstLevel:0, secondHash:0, secondLevel:0, thirdHash:0, thirdLevel:0 })
const traits = ref([]), loading = ref(false), writing = ref(false)
const backupWarningAcknowledged = ref(false)
const noTrait = { hash: 0x887AE0B0, displayName: t('wrightstone.memory.noSelection'), maxLevel: 0 }
const optionalTraits = computed(() => [noTrait, ...traits.value])
const traitMap = computed(() => new Map(traits.value.map(t => [t.hash >>> 0, t])))
const changed = computed(() => ['firstHash','firstLevel','secondHash','secondLevel','thirdHash','thirdLevel'].filter(k => (form[k] >>> 0) !== (status[k] >>> 0)).length)
function show(message, type) { emit('status', message, type) }
function sync() { Object.assign(form, { firstHash:status.firstHash>>>0, firstLevel:status.firstLevel>>>0, secondHash:status.secondHash>>>0, secondLevel:status.secondLevel>>>0, thirdHash:status.thirdHash>>>0, thirdLevel:status.thirdLevel>>>0 }) }
function selectTrait(slot, option) { form[`${slot}Level`] = option?.hash === noTrait.hash ? 0 : { first: 20, second: 15, third: 10 }[slot] }
async function refresh(syncForm=false) { loading.value=true; try { Object.assign(status, await WrightstoneMemoryGetStatus()); if(syncForm) sync(); if(!status.hooked) show(t('wrightstone.memory.status.ready'),'success'); else if(!status.selectedAddr) show(t('wrightstone.memory.status.waiting'),'success'); else show(t('wrightstone.memory.status.read'),'success') } catch(e) { show(String(e),'error') } finally { loading.value=false } }
async function enable() { window.alert(t('wrightstone.memory.warning.closeReader')); loading.value=true; try { Object.assign(status, await WrightstoneMemoryEnable()); sync(); show(t('wrightstone.memory.status.enabled'),'success') } catch(e) { show(String(e),'error') } finally { loading.value=false } }
async function disable() { loading.value=true; try { Object.assign(status, await WrightstoneMemoryDisable()); sync(); show(t('wrightstone.memory.status.disabled'),'success') } catch(e) { show(String(e),'error') } finally { loading.value=false } }
async function write() { if(!status.hooked || !status.selectedAddr) { show(t('wrightstone.memory.status.selectBeforeWriting'),'error'); return }; if(!backupWarningAcknowledged.value) { if(!window.confirm(t('wrightstone.memory.warning.backup'))) return; backupWarningAcknowledged.value=true }; writing.value=true; try { Object.assign(status, await WrightstoneMemoryUpdate({...form})); show(t('wrightstone.memory.status.written'),'success') } catch(e) { show(String(e),'error') } finally { writing.value=false } }
onMounted(async () => { try { traits.value=(await WrightstoneMemoryGetOptions()).traits || [] } catch(e) { show(String(e),'error') }; await refresh(true) })
</script>
<template><div class="memory-wrightstone"><section class="section conn"><span class="chip" :class="{on:status.hooked}">{{ status.hooked ? t('wrightstone.memory.connection.enabled') : status.found ? t('wrightstone.memory.connection.ready') : t('wrightstone.memory.connection.disconnected') }}</span><span class="hint">{{ status.hooked ? (status.selectedAddr ? t('wrightstone.memory.connection.captured') : t('wrightstone.memory.connection.select')) : t('wrightstone.memory.connection.hint') }}</span><div class="actions"><button v-if="status.hooked" class="btn" :disabled="loading" @click="refresh(true)">{{ t('wrightstone.memory.common.refresh') }}</button><button v-if="status.hooked" class="btn danger" :disabled="loading" @click="disable">{{ t('wrightstone.memory.disableReader') }}</button><button class="btn cyan" :disabled="loading" @click="enable">{{status.hooked ? t('wrightstone.memory.common.reconnect') : t('wrightstone.memory.enableReader')}}</button></div></section><section class="section" :class="{muted:!status.selectedAddr}"><header><span>{{ t('wrightstone.memory.editor.title') }}</span><button class="link" :disabled="!status.selectedAddr || !changed" @click="sync">{{ t('wrightstone.memory.common.revert') }}</button></header><div v-for="slot in ['first','second','third']" :key="slot" class="row"><span class="label">{{ t(`wrightstone.memory.editor.slot.${slot}`) }}</span><span class="current">{{status[`${slot}Name`] || t('wrightstone.memory.common.notRead')}} <small v-if="status[`${slot}Hash`]">{{ t('wrightstone.memory.level', { level: status[`${slot}Level`] }) }}</small></span><SigilMemoryPicker v-model="form[`${slot}Hash`]" :options="slot === 'first' ? traits : optionalTraits" :placeholder="t('wrightstone.memory.editor.selectTrait')" @pick="option => selectTrait(slot, option)"/><input v-model.number="form[`${slot}Level`]" type="number" min="0" max="999"/></div><footer><span>{{ t('wrightstone.memory.common.changes', { count: changed }) }}{{changed ? t('wrightstone.memory.common.unwritten') : ''}}</span><button class="write" :disabled="writing || !status.selectedAddr" @click="write">{{writing ? t('wrightstone.memory.common.writing') : t('wrightstone.memory.common.write')}}</button></footer></section></div></template>
<style scoped>.memory-wrightstone{width:100%;display:flex;flex-direction:column;gap:14px}.section{padding:14px 16px;border:1px solid rgba(255,255,255,.08);border-radius:8px;background:rgba(255,255,255,.04)}.conn{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.muted{opacity:.6}.chip{padding:3px 10px;border:1px solid rgba(255,255,255,.12);border-radius:999px;color:rgba(255,255,255,.55);font-size:.72rem}.chip.on{color:#4ade80;border-color:rgba(74,222,128,.3)}.hint{color:rgba(255,255,255,.4);font-size:.72rem}.actions{margin-left:auto;display:flex;gap:8px}.btn,.write{border:1px solid rgba(255,255,255,.16);border-radius:6px;background:rgba(255,255,255,.06);color:rgba(255,255,255,.75);cursor:pointer;padding:6px 10px}.cyan{border-color:rgba(103,232,249,.35);color:#67e8f9}.danger{border-color:rgba(248,113,113,.55);color:#f87171;background:rgba(248,113,113,.12)}.section header,.section footer{display:flex;align-items:center;justify-content:space-between;color:rgba(255,255,255,.55);font-size:.76rem;font-weight:600}.link{border:0;background:none;color:#67e8f9;cursor:pointer}.row{display:grid;grid-template-columns:50px minmax(120px,1fr) minmax(150px,1fr) 58px;gap:8px;align-items:center;margin-top:12px}.label,small,footer span{color:rgba(255,255,255,.4);font-size:.72rem}.current{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:rgba(255,255,255,.85);font-size:.8rem}.row input{width:100%;box-sizing:border-box;padding:6px;border:1px solid rgba(255,255,255,.14);border-radius:6px;background:rgba(255,255,255,.05);color:#fff}.max{color:#67e8f9;border-color:rgba(103,232,249,.3);padding:6px 4px}.section footer{margin-top:14px;padding-top:10px;border-top:1px solid rgba(255,255,255,.06)}.write{color:#4ade80;border-color:rgba(74,222,128,.4);background:rgba(74,222,128,.14);padding:7px 22px}.btn:disabled,.write:disabled,.link:disabled{opacity:.35;cursor:not-allowed}@media(max-width:720px){.row{grid-template-columns:44px 1fr 1fr 48px;gap:5px}}</style>